import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AppStateProvider from './redux/provider/AppStateProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Pixels',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppStateProvider>
          {children}
        </AppStateProvider></body>
    </html>
  )
}
